export const projectList = [
  { id: 0, name: "Gitcoin Sustainability Fund", url: "https://gitcoin.co" },
  { id: 1, name: "Ethers.js", url: "https://github.com/ethers-io/ethers.js" },
  { id: 2, name: "Dune Analytics", url: "https://www.duneanalytics.com" },
  { id: 3, name: "Tornado.Cash", url: "https://tornado.cash" },
  {
    id: 4,
    name: "Burner Factory",
    url: "https://github.com/dmihal/burner-wallet-2",
  },
  { id: 5, name: "Abridged", url: "https://www.abridged.io/" },
  { id: 6, name: "Buidler", url: "https://buidler.dev" },
  { id: 7, name: "MetaGame", url: "https://discord.gg/Hf54gd8" },
  { id: 8, name: "DeFiZap", url: "https://defizap.com/" },
  { id: 9, name: "The Commons Stack", url: "https://t.me/CSDdev" },
  { id: 10, name: "rTrees", url: "https://rtrees.dappy.dev" },
  { id: 11, name: "DAOHaus Pokemol", url: "https://daohaus.club/" },
  { id: 12, name: "rDAI", url: "https://rdai.money/" },
  { id: 13, name: "ETHTurin", url: "https://ethturin.com/" },
  { id: 14, name: "DAppNode", url: "https://dappnode.io" },
]

export const priestList = [
  {
    name: "Kevin Owocki",
    firstName: "Kevin",
    lastName: "Owocki",
    avatar: "kevin-owocki.png",
    bio: "Shiller of Colorado and philosopher king of Gitcoin",
    twitter: "owocki",
    followers: "18",
    activeDAI: "200.loading / 0.001",
    projects: [0, 8, 3],
    hatID: 72,
  },
  {
    name: "Meta Cartel",
    firstName: "Meta",
    lastName: "Cartel",
    avatar: "meta-cartel.png",
    bio: "el cartel de la meta",
    twitter: "meta_cartel",
    followers: "loading",
    activeDAI: "loading",
    projects: [7, 8, 11],
    hatID: 78,
  },
  {
    name: "Taylor Monahan",
    firstName: "Taylor",
    lastName: "Monahan",
    avatar: "taylor-monahan.png",
    bio: "Founder & CEO of MyCrypto",
    twitter: "tayvano",
    followers: "loading",
    activeDAI: "loading",
    projects: [1, 9, 0],
    hatID: 73,
  },
  {
    name: "Ameen Soleimani",
    firstName: "Ameen",
    lastName: "Soleimani",
    avatar: "ameen-soleimani.png",
    bio: "CEO at SpankChain, Summoner of MolochDAO, Heretic",
    twitter: "ameensol",
    followers: "loading",
    activeDAI: "loading",
    projects: [1, 3, 11],
    hatID: 76,
  },
  {
    name: "Alex Van de Sande",
    firstName: "Alex",
    lastName: "Van de Sande",
    avatar: "alex-van-de-sande.png",
    bio:
      "Preventing human-machines conflicts at Ethereum Foundation since 2014",
    twitter: "avsa",
    followers: "loading",
    activeDAI: "loading",
    projects: [3, 4, 12],
    hatID: 77,
  },
  {
    name: "Austin Griffith",
    firstName: "Austin",
    lastName: "Griffith",
    avatar: "austin-griffith.png",
    bio: "Hacker, breaker, builder, etc",
    twitter: "austingriffith",
    followers: "loading",
    activeDAI: "loading",
    projects: [4, 6, 0],
    hatID: 74,
  },
  {
    name: "Simona Pop",
    firstName: "Simona",
    lastName: "Pop",
    avatar: "simona-pop.png",
    bio:
      "Chief Engagement Officer at ost.com & The Pepo App, ConsenSys Grants board, Co-founder & creative of ethBounties, 1MD Steward",
    twitter: "Sim_Pop",
    followers: "loading",
    activeDAI: "loading",
    projects: [5, 10, 13],
    hatID: 75,
  },
  {
    name: "Mariano Conti",
    firstName: "Mariano",
    lastName: "Conti",
    avatar: "mariano-conti.png",
    bio: "Working at MakerDAO Foundation on #MuchCoolerDai",
    twitter: "nanexcool",
    followers: "loading",
    activeDAI: "loading",
    projects: [4, 12, 11],
    hatID: 79,
  },
  {
    name: "Griff Green",
    firstName: "Griff",
    lastName: "Green",
    avatar: "griff-green.png",
    bio:
      "In love w/ Commons Stack, Giveth, DAppNode, iden3, WhiteHatGroup, Decentral, Dogecentral (Burn Camps), EthSignals & brightID",
    twitter: "thegrifft",
    followers: "loading",
    activeDAI: "loading",
    projects: [9, 14, 12],
    hatID: 80,
  },
]
